### ISSUE TITLE
Ошибка "g[h].value is null (caused by "undefined")"

### ISSUE THREAD

**Issue by cyzzar** [e-government-ua/iForum#551]
ОС: Ubuntu, браузер Opera, Chrome
ОС: Windows XP, браузер Chrome, Firefox

Идентификация по BankId, услуга "Перереєстрація транспортного засобу при переобладнанні без зміни ном.агрегатів", https://igov.org.ua/service/1465/general/place/built-in/region/5/city/0

После заполнения всех полей выскакивает ошибка: g[h].value is null (caused by "undefined")

**Comment by allxiaa** [comment]
+1 Понадобилось воспользоваться услугой впервые на портале. попал на баг :(

После заполнения всех полей, нажал кнопку подать заявку и сразу - Помилка
g[h].value is null (caused by "undefined")
Час: "2016-07-08T06:54:55.615Z"

Так же 
Идентификация по BankId, услуга "Перереєстрація транспортного засобу при переобладнанні без зміни ном.агрегатів",
https://igov.org.ua/service/1465/general/place/built-in/region/5/city/0
ОС: вин8.1, IE11 & Firefox

**Comment by Koffeek** [comment]
@cyzzar, @allxiaa спасибо за сигнал. Проблема уже решена и в течении дня-двух обновленный код будет залит на портал.
